### ISSUE TITLE
Memory leak on calls before CacheItem is resolved

### ISSUE THREAD

**Issue by jmwilkinson** [balihoo/lru-cache-promise#2]
Once cache-item is resolved, it holds onto its array of "resolvers". Let's say you attempted to access multiple items before the resolution. Any references the fetchFunction has are kept even after the item resolves, because the item still has references to the resolvers which have references to the fetchFunction which has references to its implicit values. 

This can easily be seen with the following example:

```javascript
const LRU = require('lru-cache-promise');
const uuid = require('uuid');

var cache = LRU({maxAge: 1000 * 60 * 60 * 2});

function get_message(message) {
    return message;
}


setInterval( () => {
    let key = uuid.v1();

    for(var i = 0; i < 5; i++) {
        var value = `Data value for key on iteration ${i} could have been ${uuid.v1()}`;

        cache.getAsync(key, (key) => {
            return get_message(value);
        })
            .then((cache_item) => {
                console.log(`Fetched: ${cache_item}`);
            });
    }

}, 10000);

```

One would expect the CacheItem to resolve to just the first value- and it does- but you'll find it also keeps references to the other generated strings.

- Cache item "real" value -> `Data value for key on iteration 0 could have been <uuid>`
- Still referenced in cache item -> `Data value for key on iteration 1 could have been <uuid>`
- Still referenced in cache item -> `Data value for key on iteration 2 could have been <uuid>`
- Still referenced in cache item -> `Data value for key on iteration 3 could have been <uuid>`
- Still referenced in cache item -> `Data value for key on iteration 4 could have been <uuid>`

**Comment by balihoo-jflitton** [comment]
Thanks for the thorough write-up @jmwilkinson!  I've pushed [a change](https://github.com/balihoo/lru-cache-promise/commit/f64e4060484a842e3b29a199430e7c8b48f2c1c5) which now clears the resolvers and rejectors after they're called.  Published as version 1.0.9.
